[prompts]
Extract_Blog_Sections = "Parse meta_description, synopsis, body_content from any blog draft"
Dispatch_Offer_to_Tier_One = "Send voice or SMS offer to top drivers and wait X minutes for response"
Polish_HTML_and_apply_every_SEO_rule = "Rewrite full HTML applying structural SEO fixes and checklist"
Voice_Intake_GPT = "Act as voice call agent that takes customer order based on service type variables"
Daily_News_Summarizer = "Summarize multiple news sources and store in Airtable"
Duplicate_PDF_Detection = "Detect if uploaded PDF matches existing hash and ignore if duplicate"
Dump_Truck_Job_Structured = "Convert inbound text message into structured JSON job format"
GPT_Markdown_to_WordPress = "Convert Markdown block into WP-ready HTML with metadata"
Schedule_based_on_history = "Analyze past attendance to project likely most responsive driver"
Reconciliation_Assistant = "Guide a bookkeeper step-by-step through QBO recon workflow"
HTML_Mobile_Responsive_Fixer = "Analyze and repair HTML to display properly on small screens"
Bookkeeping_QA_Agent = "Act as a QBO reconciliation coach, asking accountant-like questions"
Image_Duplicate_Guardian = "Alert if newly uploaded image matches previous via hash check"
SEO_Markdown_Enhancer = "Inject keywords, alt-tags, internal/external links into markdown blog"
Chrome_Context_Save = "Extract selected web text as Markdown & push to Drive"
Generate_Airtable_Schema = "Define tables needed for new automation project"
Structured_PDF_Parser = "Convert PDF work order into structured fields with line-items"
News_Feed_Automator = "Summarize top 5 headlines from multiple wire sources daily"
Assign_Driver_by_History = "Choose prior most-reliable driver for repeat customer inquiry"
Make_Dot_Com_Debug_Advisor = "Given error output, diagnose module, field, or connection mismap"
Draft_Dispatch_Offer_SMS = "Compose concise negotiating SMS to offer a haul job to a driver"
Dump_truck_Tier_2_Route = "If no tier-1 driver replies, generate tier-2 SMS escalation"
Voice_Intake_Service = "Ask only required questions to book appointment via phone with user"
Re_write_for_CTA_Dominance = "Recast copy to push a strong call-before-competitors CTA"
Roles_Permissions_Designer = "Output recommended users, roles, ACL table for new SaaS"
Reconciliation_Coaching_Prompt = "Ask small-business owner questions to reconcile bank to QBO"
Chrome_Save_to_Drive_Prompt = "Capture selection and require filename from user"
Fuzzy_Name_Inferencer = "Given messy text, infer correct employee name from table"
Insert_CTA_Into_HTML = "Add branded call-to-action button at logical breakpoints in web copy"
Generate_Dispatch_Escalation_Flow = "Output tiered logic in pseudocode for Make.com scenarios"
WordPress_Troubleshoot_Prompt = "Diagnose 404 or API auth errors during Make.com publish failure"
Roles_Permissions_ACL_Builder = "Produce recommended permissions matrix for new SaaS app"
Driver_Feedback_Gathering_Prompt = "Create SMS text to ask for rating after job completion"
Master_Caution_Status_Logic = "Emit algo to change status based on deadline proximity"
PDF_Work_Order_Extract = "Convert HPM work-order links into structured JSON fields ready for Airtable"
